[versions]
kotlin = "2.4.20"
kctfork = "0.14.0"

[libraries]
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kctfork-core = { module = "dev.zacsweers.kctfork:core", version.ref = "kctfork" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
